draw_config:
  glyph_tap_size: 14
  glyph_hold_size: 12
  
parse_config:
  raw_binding_map:
    # Mouse
    '&mkp LCLK': 'ğŸ–±L'
    '&mkp RCLK': 'ğŸ–±R'
    '&mkp MB4': 'â—'
    '&mkp MB5': 'â–·'
    
    # Media
    '&kp C_VOL_UP': 'á±ğŸ”Š'
    '&kp C_VOL_DN': 'á¯ğŸ”‰'
    '&kp C_MUTE': 'ğŸ”‡'
    '&kp C_BRI_UP': 'á±â˜€'
    '&kp C_BRI_DN': 'á¯â˜€'
    '&kp C_PP': 'â¯'
    '&kp C_PREV': 'â®'
    '&kp C_NEXT': 'â­'
    
    # Modifiers
    '&kp ENTER': 'â®'
    '&kp LSHFT': 'â‡§'
    '&kp BSPC': 'âŒ«'
    '&kp SPACE': 'â£'
    
    # Locks
    '&mac_lock': 'ğŸ”’Mac'
    '&win_lock': 'ğŸ”’Win'
    
    # Bluetooth
    '&bt BT_SEL 0': 'á›’0'
    '&bt BT_SEL 1': 'á›’1'
    '&bt BT_SEL 2': 'á›’2'
    '&bt BT_SEL 3': 'á›’3'
    '&bt BT_SEL 4': 'á›’4'
    '&bt BT_CLR': 'á›’âœ–'
    '&bt BT_CLR_ALL': 'á›’âŒ«'
